### ISSUE TITLE
Get account currency

### ISSUE THREAD

**Issue by aandrey1993** [jdc68/account.service#3]
Добрый день, меня зовут Андрей и мы с @Meiendorf делаем ревью вашего тестового задания. По возникшим вопросам, будет открывать тикеты.

## Описание вопроса
На данный момент процедура для получения списка счетов выглядит следующим образом:
```sql
CREATE PROCEDURE GET_ACCOUNTS
AS
BEGIN
    SET NOCOUNT ON;

    SELECT * FROM dbo.Accounts
END
GO
```

При таком раскладе, по каждому счету вернется Id валюты, вместо того чтобы возвращалась информация из столбца `currency`

## Задача
Внесите соответствующие изменения чтобы до пользователя возвращалась соответствующая валюта счета (MDL, USD ..) вместо Id. 

Это можно сделать, добавив JOIN в запросе счетов с таблицей `Currencies` (наиболее предпочтительный вариант), либо описать связь на уровне hibernate Entity и заполнять валюту при маппинге в DTO объект.

Если возникнут какие-то трудности, вопросы, можете оставить их в комментариях.

**Comment by jdc68** [comment]
Добрый день.

Спасибо, уже работаю
